- README.md
- index.js
Added ACL property so you can define what the acl for the uploaded files will be.
As the used S3 library only syncs new files, this will only work when uploading or syncing new files. Existing files will keep their current ACL.
> Add ACL property

- README.md
- index.js
- package.json
This will enable the customization of props for uploaded files.
Ex.:
```yaml
custom:
s3Sync:
- bucketName: my-bucket
localDir: dist/
params:
- index.html:
CacheControl: 'no-cache'
```
> Add possibility to change props per key using globs

- index.js
Currently the logic says that bucketPrefix should be set if bucketPrefix does not exist, I removed the !, correcting the logic.
> fix logic for bucketPrefix

- index.js
This PR is aimed at fixing https://github.com/k1LoW/serverless-s3-sync/issues/11.
Currently, the plugin loads a new AWS SDK instance which breaks some of the functionality added by the serverless framework when it initializes the SDK.
> Use AWS SDK provided by serverless

- README.md
- index.js
I needed to have some HTML files on S3 without extension. But files without extension get uploaded as `application/octet-stream`, which triggers a download instead of displaying the files in the browser.
This PR adds support for the `defaultContentType` property. When defined, files without extension or with unrecognized extensions will be uploaded using the given content type.
> Add support for defaultContentType property

- index.js
monolambda/s3 client accepts an options argument, which is an object and not an instance of s3 client. I found this issue when I was trying to use the plugin for syncing with another profile (non default). Because s3Client was not passed correctly it defaulted to the `AWS.S3` with default profile, which resulted in AccessDenied error.
> Fix passing s3Client to `monolambda/s3`

- index.js
This PR removes the reference to the s3Sync config that existed in the constructor.
The reason this has to be done is that variable references are not yet replaced when the plugin constructor is called, as stated in the [Serverless docs](https://serverless.com/framework/docs/providers/aws/guide/plugins/):
> Note: Variable references in the serverless instance are not resolved before a Plugin's constructor is called, so if you need these, make sure to wait to access those from your hooks.
By moving the config references only to the hooks execution, the problem is solved. This PR probably addresses issue #6 too.
> Remove config reference in constructor

- index.js
- package-lock.json
- package.json
There is a security vulnerability in this package's dependencies
```bash
$ npm audit
=== npm audit security report ===
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │ …
```
> Updated dependencies to fix mime package vulnerability

- index.js
- package-lock.json
- package.json
Hey all,
This fixes the issue with CacheControl values not making it into s3 metadata.
> Fixes k1LoW/serverless-s3-sync#31 by ignoring the first key (glob).

- README.md
- index.js
- resolveStackOutput.js
This PR allows the name of a bucket to optionally be fetched from the stack output. This is helpful when the name of the bucket is not known before the stack is created. In such cases the user can now write the name of the bucket as an Output value and provide the Output key as a `bucketNameKey` property.
This fixes issue #6.
The implementation is inspired from the [serverless-cloudfront-invalidate](https://github.com/aghadiry/serverless-cloudfront-invalidate) plugin which does something very similar.
NOTE: Most of these changes are whitespace/indentation so in the diff view you might choose Diff Settings -> Hide whitespace changes.
> Adds support for fetching the bucket name from the stack output

- index.js
This PR should resolve #35 
this process will ensure metadata is up to date with every s3sync call.
after the s3sync:sync process the `s3sync:metadata` process follows.
this will take a look at the *custom.s3Sync[n].params* values, and match the globs based on the configuration of the *custom.s3Sync[n]* parameters.  Once it knows all of the files that have metadata altered by this file, it will perform a s3api call on **copy-object**, which is nicely wrapped in the **@oauth0/s3** lib. 
There shouldn't exactly be any issues with using **copy-object**, one thing to note is that the **copy-object** api call will explicitly alter the readability of the file.  For example, if you call the s3api **copy-object** on a *public-read* acl s3 file, and you don't explicitly give it an acl, it will …
> Solution for #35 - update Cache-Control headers even if files don't change

- index.js
- package.json
This was missed and intended to be part of the original release.
If we want to run `sls s3Sync` then we expect it to sync the metadata even if the files have not changed (md5 is the same).
This behavior should also happen with `sls deploy`, as in some cases there are developers who make content changes that are specific to the file metadata, and not to the file itself.  We want to ensure that when committed to a repository, and CI/CD is ran (using `sls deploy`) then it should ensure the state of the metadata matches the intended state of the deployment.
Thanks
> intended the syncMetadata to run with every deploy as well as s3sync

- index.js
This makes the trailing slash optional on the `localDir` configuration value as requested in #41.
The file sync already handles values without a slash; this adds the slash (only if required) when syncing meta data.
> Allow optional trailing slash on the localDir configuration value

- index.js
This PR will ensure that the `bucketPrefix` (if defined and not empty) is prefixed by a slash and does not contain a trailing slash.
> Detect slashes on bucketPrefix and fix as required

- index.js
I had issues on Windows with backslashes in the file path when synchronizing files with caching metadata.
> When syncing metadata replace every path separator with '/' 

- index.js
I get an error when deploying with the new bucketNameKey feature.  this fixes it.
> support bucketNameKey in syncMetadata

- index.js
Right now, The Serverless Framework Enterprise has released as additional features of the framework.
https://dashboard.serverless.com/
Using the following functionality, you don't need to directly add AWS Credentials to CI/CD env since it allows you to deploy from the AWS account of the enterprise using the trusted relationship of AWS IAM between each AWS accounts.
https://serverless.com/framework/docs/dashboard/access-roles/
To support for that, this plugin needs to use `provider.cachedCredentials` which the credentials from the enterprise is in.
You will be able to use the credentials from the enterprise if `provider.cachedCredentials` is not null. if not, using the current credentials system if merging this PR.
仕事で使うのでよろしくおねがいします！
> Support credentials from Serverless Framework Enterprise

- index.js
I'm attempting to have a single source project containing both React app and serverless spec, and have `sls deploy`:
1. Deploy backend resources to AWS
2. Use [`@lucas-carneiro/serverless-stack-output`](https://github.com/lucas-carneiro/serverless-stack-output) to update React app with details from CloudFormation
3. Run `npm build`
4. Use `serverless-s3-sync` to copy the React `build/` directory up to S3.
After getting the output of the CloudFormation stacks written, I need to do something to update the React runtime. I've tried to use [`serverless-plugin-scripts`](https://github.com/mvila/serverless-plugin-scripts), but unfortunately I don't think the dynamic hooking and ordering can be made to work. It'd also be nice to avoid an extra dependency.
This PR adds a `preCommand` option to …
> Add a `preCommand` option for running scripts before sync

- index.js
Solves a bug that I introduced in previous pull request #61: when `bucketTags` setting is not specified, the plugin would still issue get/putBucketTagging requests to S3. These requests are unnecessary. 
Furthermore (as it was my case), they were introducing a breaking change due to the fact that a deployment that worked before may fail to deploy if it does not have s3:PutBucketTagging and s3:GetBucketTagging permissions for the IAM role that executes the deployment.
Now we're skipping the bucket tag actions completely when bucketTags node is missing from the config.
> Skip get/putBucketTagging requests when bucketTags option is not configured

- README.md
Improved the docs a bit, to show how one can reference outputs from another stack.
Provides a good-enough alternative for supporting Fn::ImportValue, this way you can maybe close #19.
> Add example of how to reference bucket name from another stack

- resolveStackOutput.js
I always get the error message:
```
S3 Sync: Syncing directories and S3 prefixes...
Config Error -------------------------------------------
ConfigError: Missing region in config
at Request.VALIDATE_REGION (C:\snapshot\serverless\node_modules\aws-sdk\lib\event_listeners.js:92:45)
at Request.callListeners (C:\snapshot\serverless\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
at callNextListener (C:\snapshot\serverless\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
at C:\snapshot\serverless\node_modules\aws-sdk\lib\event_listeners.js:86:9
at finish (C:\snapshot\serverless\node_modules\aws-sdk\lib\config.js:379:7)
at C:\snapshot\serverless\node_modules\aws-sdk\lib\config.js:397:9
at SharedIniFileCredentials.get (C:\snapshot\serverless\node_modules\aws-sdk\lib\credentials.js:1 …
```
> Fixed bug with resolving region in resolving stack output

- index.js
I faced the problem that the sync was finished but the syncMetadata won't be finished. Because syncMetadata will find all files (even though if a user specified the bucket), non-exist localDir was caused the error. So, I fixed the getLocalFiles to ignore non-exist files.
> Ignore error if a file/dir did not exist when syncMetadata

- index.js
Purpose: To upload a file only in a specific environment.
**How to use:**
in serverless.yaml:
```yml
custom:
s3Sync:
- bucketName: my-bucket
localDir: files
params:
- "prod.json":
OnlyForEnv: prod
- "stg.json":
OnlyForEnv: stg
- "dev.json":
OnlyForEnv: dev
```
The `prod.json` will be uploaded only in the `prod` environment, other files too.
> Add `OnlyForEnv` parameter directive

- README.md
- index.js
PR adds support for serverless-offline [https://www.serverless.com/plugins/serverless-offline](https://www.serverless.com/plugins/serverless-offline) with serveless-s3-local [https://www.serverless.com/plugins/serverless-s3-local](https://www.serverless.com/plugins/serverless-s3-local)
To use, move existing buckets into a `buckets` field and include an `endpoint` field in the `custom.s3Sync` section of `serverless.yaml`.
PR supports existing `serverless.yaml` configuration for backwards compatibility.
> add serverless-offline + serverless-s3-local support

- README.md
- index.js
Apply --nos3sync flag when running `serverless remove` as well.
One use case is when I remove a stack with an S3 bucket sync-ed with serverless-s3-sync and the stack removal fails, CloudFormation leaves behind a partially-removed stack (with the S3 bucket already deleted). Trying to remove it again gives an error because serverless-s3-sync tries to clear the non-existing bucket.
In my case, I am already using serverless-s3-remover (because some buckets are sync-ed from other repositories). That plugin ignores all errors. So I want to disable bucket clearing on remove by serverless-s3-sync, since the other plugin already handles it.
> Take --nos3sync into account during serverless remove

- getAwsOptions.js
- index.js
- resolveStackOutput.js
Hi This fixes problems when authed only using Serverless' `SERVERLESS_ACCESS_KEY` env variable, AWS credentials stored in Serverless dashboard. (not with locally stored aws credentials or aws-cli)
S3 sync was working this way only with `bucketName` and not with `bucketNameKey`, due to these differences in credentials. This MR only reuses the method originally from `client()` method again in `resolveStackOutput`. It doesn't change any logic (including the comments).
I believe this is also related/possible fix to https://github.com/k1LoW/serverless-s3-sync/issues/66
> Fix: Unify getting aws / serverless credentials

- index.js
This is an alternative to #83 that keeps the plugin CLI option working with Serverless v3.
See discussion here: https://github.com/serverless/serverless/discussions/10618
> Extend deploy/remove commands with nos3sync option so that it can be used with Serverless v3

- README.md
- index.js
- package-lock.json
- package.json
- remove chalk from dependencies, no longer necessary
- add serverless as peerDependency
Closes: #95
NOTE: this is a breaking change (no longer works with serverless v2.x) and must be released as a new major version.
See also https://github.com/serverless/serverless/discussions/10670#discussioncomment-2141521 for why the console log has been moved to verbose and limited to minimum.
> Replace deprecated serverless.cli.log() calls with logging API and mark the plugin as requiring Serverless v3.x

- index.js
Those files upload fine in the sync phase but fail to update the metadata. I'm not sure why this is done in 2 steps vs 1 on sync. Thanks for creating this plugin!
> Fix metadata update failing when object's keys contain some characters like spaces and +

- index.js
Just like the serverless framework itself, let's ignore `.DS_Store` files. I don't see a reason why they should even be synced.
> ignore `.DS_Store` files by default

- index.js
In older versions of serverless-offline we could use the nos3sync command when starting our serverless application for local development.  
This however no longer works and we get the error "Detected unrecognized CLI options: "--nos3sync"
This just updates the allowed commands so that the "--nos3sync" option will work with serverless offline.
> support nos3sync command when using servereless-offline

- README.md
- index.js
There's a bug where if you have a disabled sync rule, like so:
```
s3Sync:
- bucketName: ${self:custom.hostingBucketName}
- bucketName: ${self:custom.storybookBucketName}
enabled: false
localDir: storybook-static
```
And you try to run `sls remove`, if that bucket doesn't exist in the CloudFormation stack, s3-sync throws the following error:
```
Error:
NoSuchBucket: The specified bucket does not exist
at Request.extractError ([snipped]/lib/node_modules/serverless/node_modules/aws-sdk/lib/services/s3.js:715:35)
at Request.callListeners ([snipped]/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
```
The problem is due to the fact that in the clear command, the process doesn't exit out early if the disabled flag is set. The fix  is simply to add a guard …
> Ensure that disabled rules don't execute while running a sls remove

- README.md
- index.js
Adds a 'hooks' option to allow providing a list of lifecycle hooks which s3 sync will be triggered on.
> Provide hooks configuration option to allow binding to alternative lifecycle hooks
